import '@fortawesome/fontawesome-free/css/all.min.css';
import 'bootstrap/dist/css/bootstrap.rtl.min.css';
import '../css/contact.css';
import '../css/search.css';
import '../css/payment.css';
import '../css/checkout.css';
import '../css/product.css';
import '../css/style.css';
import 'bootstrap/dist/js/bootstrap.bundle';
